### PR TITLE
Fixes #10 - Use Swagger Auth

### LINKED ISSUE #10: Set Swagger to use the built-in security definition
At the moment a custom operation filter has been implemented so that an Bearer token is required on all requests. Swagger instead has built-in functionality for handling this and we can migrate to that instead.

The implementation is found within `Startup.cs`. An example of the code can be found here:

```
x.AddSecurityDefinition("Bearer", new ApiKeyScheme
{
	In = "header",
	Description = "Please insert JWT with Bearer.",
	Name = "Authorization",
	Type = "apiKey"
});

x.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
	{ "Bearer", new string[] { } }
});
```

### PR DESCRIPTION
**Pull request by jamesbondev**
Swagger now uses in built security definition and requirement for including bearer token to all api requests once set. Old AuthHeaderParameter has been removed.

### CODE REVIEW

**Comment by hssahan** [comment]
Does this mean we still need to write "bearer" in the auth token?

**Comment by jamesbondev** [comment]
Yes, same as previous. The token must be prefixed with “Bearer”.

**Comment by hssahan** [comment]
So I suppose the audit attribute will still work as it did before as it tries to get the auth header etc

Foods.Service.Api.FilterAttributes.Audit

**Comment by jamesbondev** [comment]
Yeh the only change is to Swagger and how it includes the token, the api will still receive the expected “Authorization” header like normal.

**Review by hssahan — APPROVED** [review]

**Pull request merged**
